### ISSUE TITLE
error on 4.18.15 Archlinux

### ISSUE THREAD

**Issue by muhviehstah** [antonio-petricca/paragon-ufsd-ntfs-driver-porting#1] opened 2018-10-20 05:59 UTC
make driver_install / modprobe/insmod fails with

ufsd: Unknown symbol vfs_read (err 0)

building the driver is without a warning / error

**Comment by antonio-petricca** [comment] 2018-10-20 07:05
Please, let me some time to reproduce your issue on a virtual machine (I am on Linux Mint).

I will back with an answer as soon as possible.

Thank you for your attention.

Antonio

**Comment by antonio-petricca** [comment] 2018-10-21 21:13
I reproduced the issue on "Manjaro with kernel 4.18.16".

When I run `make driver` I get this error:

> FATAL: modpost: GPL-incompatible module ufsd.ko uses GPL-only symbol 'vfs_read'

Please let me to discover how to fix it.

**PS**: on Linux Mint it does not happen!

**Comment by antonio-petricca** [comment] 2018-10-21 21:19
Solution found! I am going to release it by tomorrow...

**Comment by antonio-petricca** [comment] 2018-10-22 04:36
Patch released. Please tell me if it works for you too in order to close the issue.

**Comment by antonio-petricca** [comment] 2018-10-24 10:50
Any feedback?!

**Comment by ianmatt** [comment] 2018-10-28 11:05
> make driver_install / modprobe/insmod fails with
> 
> ufsd: Unknown symbol vfs_read (err 0)
> 
> building the driver is without a warning / error

this is likely due to the following:
1. vfs_read no longer being exported (EXPORT_SYMBOL(vfs_read) in fs/read_write.c) since 4.14
AND
2. running a kernel that was compiled with CONFIG_IKCONFIG_PROC
code is in config_check.c:
```
#if ((defined CONFIG_IKCONFIG_PROC) && (defined CONFIG_ZLIB_INFLATE))
  crc = ufsd_calc_config_hash();
#endif
```
where it calls
```
unsigned long __init ufsd_calc_config_hash(void){
...
    set_fs(get_ds());
    ret = vfs_read(filp, in, IN_SIZE, &offset);
    set_fs(oldfs);
...
}
```
since all that config check is only informational (it will still load if unmatched), a quick hack (not tested) would be to replace _#if ((defined..._ with _#if 0_ skipping that code regardless (it's skipped on most kernels at module compile time since most don't use CONFIG_IKCONFIG_PROC)

**Comment by muhviehstah** [comment] 2018-10-30 08:17
Thank you,

the module builds without error on 4.19.0-arch1-1-ARCH

but the same error when installing/modprobing

 ufsd: Unknown symbol vfs_read (err -2)

**Comment by antonio-petricca** [comment] 2018-10-30 08:20
I understood, I am going to try again... Please be patient. ;)

**Comment by ianmatt** [comment] 2018-10-30 08:44
It's due to vfs_read being unexported since kernel 4.14 and only happens when kernel was build with CONFIG_IKCONFIG_PROC (there's a preprocessor #if in config_check.c that checks for this flag and will only include the checksum function in this case). Since this only informational (will still continue even with unmatched config) a quick fix would be to skip the runtime checksum with #if 0 or use kernel_read or ...

**Comment by muhviehstah** [comment] 2018-10-30 22:24
no problem, take your time

the symbol comes like ianmatt says from the config_check.c file

had tried to replace vfs_read with kernel_read before. after this i was able to load the module but mount didn't recognized the fstype ufsd

maybe i had some userspace problems because i'm owning the pro version. it comes with userspace tools. 

a pure waste of money to buy this as an archlinux user hehe

**Comment by ianmatt** [comment] 2018-10-30 22:44
> had tried to replace vfs_read with kernel_read before. after this i was able to load the module but mount didn't recognized the fstype ufsd

worked here with kernel_read, but if anything try to replace the existing preprocessor line that checks for CONFIG_IKCONFIG_PROC in config_check.c with _#if 0_ this way the whole config runtime check will not be compiled in (vfs_read too), pretty useless stuff imo
> maybe i had some userspace problems because i'm owning the pro version. it comes with userspace tools

userspace tools (chkntfs/mkntfs) have nothing to do with the ufsd module, you can actually use one w/o the other. you should check in /proc/filesystems for ufsd after (manually) loading the ufsd.ko module and if there try a manual mount _mount -t ufsd /dev/sda2 somedir_ replace sda2 and somedir as appropriate

clone this git then run the script and simply edit that #if line before doing the make driver, should work

**Comment by antonio-petricca** [comment] 2018-10-30 22:54
@ianmatt if you wish you could send me a pull request with your changes in order to try your fix on debian kernels distribution.

**Comment by muhviehstah** [comment] 2018-10-30 23:18
i will create an AUR dkms package when it works.  

apply the patches with the pro version fails because it have additional source files even for building the driver. 

maybe you can help to fix this, 

providing patches for the pro version too without providing the source tarball would be a nice feature for your project :)

greetings

**Comment by antonio-petricca** [comment] 2018-10-31 06:58
I have just reproduced the issue on Arch and kernel 4.18.16. I am going to fix it...

**Comment by antonio-petricca** [comment] 2018-10-31 16:16
Hi, I have just released [the fix](https://github.com/antonio-petricca/paragon-ufsd-ntfs-driver-porting/tree/4.19-hotfix-01-archlinux).

**Closed by antonio-petricca** 2018-10-31 16:16 UTC
Labels: bug, good first issue, solved

**Comment by muhviehstah** [comment] 2018-11-02 23:30
`[310115.658175] ufsd: driver (UFSD_HEAD lke_9.5.4_r312115_b132, acl, ioctl, sd2(5), car) loaded at 00000000db9da87b
[310115.658176] ufsd: ported on kernels 4.13 to 4.19 by Antonio Petricca @ 2018 (https://github.com/antonio-petricca/paragon-ufsd-ntfs-driver-porting).
[310115.658177] ufsd: PAGE_SIZE=4K, THREAD_SIZE=16k
[310115.658195] ufsd: Can't read file.
[310115.658195] ufsd: CRC calculation failed.
[310115.658197] ufsd: Kernel .config hash: original 0x8a0551c3, current can't check.
[timo@Funix sources]$ uname -a
Linux Funix 4.19.0-arch1-1-ARCH #1 SMP PREEMPT Fri Oct 26 12:34:53 UTC 2018 x86_64 GNU/Linux
[timo@Funix sources]$ lsmod|grep ufsd
ufsd                  643072  0
`

**Comment by antonio-petricca** [comment] 2018-11-03 09:08
I have noticed it, but I suppose you can ignore it. I tried it: the driver works for me as expected.
